### PR TITLE
Allowed middleware registered externally to use partial signins via cookie authentication

### PR DESCRIPTION
**Pull request by alhardy**
We have included a user migration flow on login from an old auth system of ours, this migration flow and other custom pages we require like forgot passwords, forcing a users password to be reset etc have been implemented as owin middelware components and registered with idsrv's autofac container. 

Having these components run after ```app.ConfigureCookieAuthentication(..)``` allows us to retrieve a partially authenticated ClaimsIdentity in our middleware components through ``` context.Environment.GetIdentityServerPartialLoginAsync()```

### CODE REVIEW

**Comment by leastprivilege** [comment]
You broke the tests.

**Comment by brockallen** [comment]
We can't move the DI system after Cors and Cookies -- both of them depend on it.

**Comment by alhardy** [comment]
@leastprivilege Yes, all 423 tests run on a local build?

@brockallen the container is already built at this point, ``` app.UseAutofacMiddleware(container);``` is just resolving and executing any middleware registered with the container?

**Comment by alhardy** [comment]
@brockallen OK, I see your point here. How do you guys suggest registering custom controllers/middleware allowing access to dependencies registered by IdentityServer?

**Comment by brockallen** [comment]
You can always use the `ResolveDependency` OWIN extension.

https://identityserver.github.io/Documentation/docsv2/advanced/owin.html

**Comment by alhardy** [comment]
In cases where we need the ClaimsIdentity for a partially logged in user, how would we do that?

**Comment by brockallen** [comment]
There's another OWIN extension method on that list called `GetIdentityServerPartialLoginAsync`.

**Comment by alhardy** [comment]
Thanks for the quick replies Brock. 

Yes, that's the guy I'm using but I end up getting back null as the ClaimsIdentity. This would be because my middleware was running before the cookies middleware, I've tried awaiting next in my middlware to have idsrv do it's usually thing before I call ```GetIdentityServerPartialLoginAsync``` but still no luck.

I'll keep digging.

**Comment by alhardy** [comment]
@brockallen [this](https://github.com/IdentityServer/IdentityServer3/commit/257336526fdaecc4e823ef1dd266ec68618a2726) fixes my issue, which is what I was trying to get at in my previous commit. Do you see any issues here?

**Comment by alhardy** [comment]
@brockallen last commit is related to [this issue](https://github.com/IdentityServer/IdentityServer3/issues/2398) i was having.

**Pull request closed without merging**
