### PR TITLE
Update app.js

### PR DESCRIPTION
**Pull request by shabatinT**
We have a lot of customers who still using IE8. But IE8 doesn't support "textContent" http://www.w3schools.com/jsref/prop_node_textcontent.asp

With proposed change all should work even under IE8.

Thanks.

### CODE REVIEW

**Comment by brockallen** [comment]
thanks!

**Comment by gnjack** [comment]
This fix does not seem to work in IE8 for me?

typeof returns a string https://msdn.microsoft.com/library/259s7zc1(v=vs.94).aspx, so this line:
```javascript
if (typeof(modelJson.textContent) !== undefined) {
```
should be:
```javascript
if (typeof(modelJson.textContent) !== "undefined") {
```

**Comment by shabatinT** [comment]
Yes, you are right. I've missed quotes.

**Comment by brockallen** [comment]
Mind submitting a fix?

**Comment by shabatinT** [comment]
I thought that @gnjack did it. If not, can you please fix it?

**Pull request merged**
