### PR TITLE
Add support for X.509 client certificate authentication on token endpoint

### PR DESCRIPTION
**Pull request by leastprivilege**
This is a breaking change (signature of IClientSecretValidator needs to be changed)

### CODE REVIEW

**Comment by bfancett** [comment]
I've been waiting for this for a while, sorry to see its waiting unail 2.0.  Most government organizations don't use user name and password, and instead use clisn't certs.  This leaves us developers in a pickle when things like Thinktecture Idsrv come out but we can't implement because it doesn't support ISS with require client certificates turned on.  

Maybe there is a way to do this already that I'm just not aware of.  I know there are thousands of potential Idsrv implementations waiting on this.

**Comment by leastprivilege** [comment]
You can use the ClientCertificate branch if it is really urgent. Maybe those thousands of implementors want to sponsor us to give certain features a higher priority.

Anyway - it will be a breaking change, and we try to be careful about that.

**Comment by johnkors** [comment]
@leastprivilege I know this is a tad late to the game to be pointing this out, but about the reason for this to be a breaking change is down to the APIs (public interface method signatures) being a bit fragile when it comes to extensibility. 

In general, instead of passing strings (in this case,```ClientId, ClientSecret```) , strongly typed objects as params would provide for more extensiblity in future versions by not needing to change the interface

```
Task<bool> ValidateClientSecretAsync(Client client, string secret);
```

vs

```
Task<bool> ValidateClientSecretAsync(ValidationComposite comp)
```
(naming just an example)

I see that's the change you're going for here as well, but it might be an idea to do the same for other interfaces passing strings (or 3-4 strongly typed parameters) as well, so they are easier to extend in future versions.

I might be missing some other API design reasoning you have, though.  Just some thoughts.

**Comment by leastprivilege** [comment]
You are right - we mainly were focusing on getting v1 out of the door. Now it is time to collect ideas how we can improve things.

**Comment by leastprivilege** [comment]
rolled into v2 branch

**Comment by tofutim** [comment]
Is there instruction on how to use this?

**Comment by leastprivilege** [comment]
not right now - work in progress.

**Comment by tofutim** [comment]
Is there a test for the client certificate?

**Pull request closed without merging**
