### PR TITLE
Add Kentor SAML2 Middleware to example config

### PR DESCRIPTION
**Pull request by AndersAbel**
- Configured to use the public stubidp.kentor.se test IDP.

### CODE REVIEW

**Comment by leastprivilege** [comment]
how about we do a separate sample for that?

**Comment by leastprivilege** [comment]
or maybe not - let me think about that...

**Comment by AndersAbel** [comment]
Whatever you see fit - I can set up a separate project if you prefer that.

**Comment by leastprivilege** [comment]
yea - I'd prefer a separate sample

copy this one:

https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/WebHost%20(minimal)

**Comment by leastprivilege** [comment]
OK?

**Comment by leastprivilege** [comment]
..or self-host. whatever you prefer

**Comment by AndersAbel** [comment]
Sure, will do and get back with another PR.

**Pull request closed without merging**
