### PR TITLE
Moved Autofac configuration to an Autofac module

### PR DESCRIPTION
**Pull request by willieferguson**
There are several issues (e.g. #498 and #828) which deals with more control over the AutoFac container. In these and my use case, IdentityServer is used as a library inside a existing application.

This PR move all Autofac configuration into an public Autofac Module, allowing applications that use Identity Server as a library, to configure IdentityServer.

### CODE REVIEW

**Comment by leastprivilege** [comment]
you are exposing an internalized type. tests failed.

**Comment by willieferguson** [comment]
Implementing IModule is just a loophole in the test. Users of the Nuget package will still not be able to use AutofacModule because the ILMerge'd IModule won't be the same as the one from Autofac proper. 

This is not a problem for me because I build an internal NuGet package which doesn't ILMerge anything but take a dependency on them. 

I understand that you don't want to take a bunch of dependencies for the trivial case, but for most non-trivial use cases you would take a dependency on most of these packages anyway.

**Comment by brockallen** [comment]
We didn't design for the assumption " IdentityServer is used as a library inside a existing application".

**Comment by leastprivilege** [comment]
@brockallen close?

**Comment by brockallen** [comment]
I suppose so.

**Pull request closed without merging**
