### PR TITLE
Introspection endpoint

### PR DESCRIPTION
**Pull request by leastprivilege**

### CODE REVIEW

**Comment by leastprivilege** [comment]
Tests missing - will be added.

**Comment by brockallen** [comment]
Spec still seems to be in flux WRT scope authentication....

**Comment by leastprivilege** [comment]
They are debating if authentication is a MUST or SHOULD. We can add a config switch for that.

**Comment by leastprivilege** [comment]
but we can also postpone to 2.1 - i don't mind.

**Comment by leastprivilege** [comment]
I think we should add the minimal version to 2.1 with 

* make scope authentication optional (endpoint setting) - but default to true
* think about advanced features like sliding expiration on validation

**Comment by brockallen** [comment]
Should client credentials be allowed in the POST body (in addition to Authorization header)?

**Comment by leastprivilege** [comment]
Depends on the registered validators. Right now they are allowed.

**Comment by brockallen** [comment]
Ok, I tested with my new RO JS sample and it wasn't allowing via the POST body. I can show you later.

**Comment by leastprivilege** [comment]
Introspection or revocation?

**Comment by brockallen** [comment]
Ok, I tracked it down -- I think it's back to our issue where POST body being read via Web API vs. OWIN.

**Pull request merged**
