### PR TITLE
fixed core HttpAssets paths in bundle

### PR DESCRIPTION
**Pull request by jhaker**

### CODE REVIEW

**Comment by brockallen** [comment]
1) we don' accept PRs to master
2) why is this change necessary? are you getting errors? are you using an older web essentials? it's working for me.

**Comment by jhaker** [comment]
1)sorry. this is the first time...should I have created my own branch?2)yes, getting build errors. I pulled a new version down this morning and it failed when building with VS 2013. I changed the paths and it worked. 
-Jon

**Comment by brockallen** [comment]
Hmm, then something else is amiss if you can't build. It's working for everyone else. Again -- check your version of Web Essentials?

**Comment by jhaker** [comment]
Updating Web Essentials fixed my issue. Thanks for the help!
Great project btw. I plan on contributing and will start looking for ways to get involved. 
-Jon

**Pull request closed without merging**
