### PR TITLE
Add support for cookie session store

### PR DESCRIPTION
**Pull request by mvalipour**
@tarunvd @flytzen

Re: #1683 

We came up across this scenario where we need to set the session store to be used for cookie authentication that IdentityServer utilizes.

This change set aims to add support for this.

### CODE REVIEW

**Comment by brockallen** [comment]
Ok, I'll look into it. Thx.

**Comment by brockallen** [comment]
Should we also store the AuthenticationProperties? I worry that we lose something if we're ignoring that data.

**Comment by mvalipour** [comment]
You are very right, in fact the store, must read in/out the whole ticket (which is identity+properties). I will make these changes shortly

**Comment by brockallen** [comment]
Also can you update to latest while you're at it? Thx

**Comment by mvalipour** [comment]
Sure, do you guys accept only `rebase`? or is merge upstream is alright?

**Comment by brockallen** [comment]
Whatever works.

**Comment by mvalipour** [comment]
OK, I rebased these changes with the latest upstream dev branch. Hope it's alright now.

**Comment by brockallen** [comment]
Thanks for updating this, but I don't think this works -- the `AuthenticationTicket` is a Katana type that we internalize when we build so it's not public. We need a custom class to model that, or we just expose the ClaimsIdentity and Dictionary in the new `IAuthenticationSessionStore`.

**Comment by brockallen** [comment]
Looks like we can get away with just the `Dictionary` since the Katana `AuthenticationProperties` class implements all its strongly typed properties in terms of the `Dictionary`.

**Comment by mvalipour** [comment]
ah! I knew there was a reason I didn't make it like that in the first place! :D
I've made the changes needed (as you described) and the test should be passing now.

**Comment by brockallen** [comment]
Looks good, thanks.

**Pull request merged**
