### PR TITLE
Identity token validation endpoint tests

### PR DESCRIPTION
**Pull request by mderriey**
#387

### CODE REVIEW

**Comment by brockallen** [comment]
Were these related to an open issue? Can you provide a little context, please? Thx

**Comment by mderriey** [comment]
Yeah, issue #387 as noted in the PR comment ;-)
Let me know how they look to you.
I wanted to test the endpoint **only** so ended up "mocking" the token vlaidator. If this is not what you expect, feel free to provide feedback.
Thanks

**Comment by mderriey** [comment]
If there's anything wrong in the PR, can you please let me know?
I'll be more than happy to edit it so it complies with your expectations.

**Comment by brockallen** [comment]
We're very busy, so just haven't had time to look it over yet. Perhaps end of this week.

**Comment by mderriey** [comment]
No worries, thanks.

**Comment by brockallen** [comment]
thanks!

**Comment by mderriey** [comment]
You're welcome. I have the access token validation endpoint tests pending. I'll submit it at the beginning of next week.

**Comment by brockallen** [comment]
sounds good!

**Pull request merged**
