### PR TITLE
Implement Proof Key with Code Exchange

### PR DESCRIPTION
**Pull request by mderriey**
Associated with #2378 

Let me know how you feel about it.
Cheers!

### CODE REVIEW

**Comment by mderriey** [comment]
Could you also have a look at [this commit](https://github.com/mderriey/IdentityServer3/commit/be2fb8f0db940cec8cb088ae5e0f647b0e1e5b90) and tell me if you're interested in it?

The spec states [here](https://tools.ietf.org/html/rfc7636#section-4.4.1) that the `error_description` value should explain what went wrong in some cases. I'm not sure you want to bring this in.

Thank you

**Comment by leastprivilege** [comment]
thanks! Will have a look soon.

**Comment by leastprivilege** [comment]
This looks very good - Brock and I are meeting for a final review later.

**Comment by brockallen** [comment]
Excellent PR -- thanks! Just those few minor questions to discuss.

**Comment by mderriey** [comment]
Thanks for the extensive feedback, it's really appreciated.
I'll work on this quickly.

Did you have a chance to have a look at [that commit](https://github.com/mderriey/IdentityServer3/commit/be2fb8f0db940cec8cb088ae5e0f647b0e1e5b90) that includes `error_description` for certain scenarios? It's not merged yet into this branch but if yo want it, I'll do it.

Thanks!

**Comment by brockallen** [comment]
Yea, I think the error description stuff looked fine as well. 

Again, great PR and thanks for all the tests.

**Comment by mderriey** [comment]
I made some changes related to your comments.
I ended up hashing the code challenge even though the in-memory authorization code store is used.

Let me know if it's OK with you.

Thanks again :+1:

**Comment by brockallen** [comment]
Looks good to me. @leastprivilege ?

**Comment by leastprivilege** [comment]
looks good!

good work! thanks!

**Pull request merged**
