### PR TITLE
Updated the Serilog version from 1.5.12 to 1.5.14 in order to build t…

### PR DESCRIPTION
**Pull request by DecimusN7**
…he solution. Solution now builds with no more errors - cloned using Visual Studio 2015.

### CODE REVIEW

**Comment by brockallen** [comment]
What errors?

Also, we don't take PRs to master.

**Comment by DecimusN7** [comment]
Nuget package manager could not install the 1.5.12 package, saying it was not found. As a result It gave 5 errors on missing references. Checking in the package manager under VS 2015, it indicated there is an update to Serilog. I had the package manager upgrade it, and the solution built successfully.

Also, which branch would I need to fork from to submit a PR?

Sincerely,

Decimus.

**Comment by DecimusN7** [comment]
Nevermind... I didn't see the Contribution document till I was using the GitHub website... cloning and adding to VS 2015 does not reveal these files. My bad.

Thanks.

**Comment by brockallen** [comment]
Ok, so you're all set and we can close this PR?

**Comment by DecimusN7** [comment]
Yes, I'll submit an issue and we can take it from there.

Thanks!

>>>>

**Pull request closed without merging**
