### PR TITLE
Update AngularJS to latest stable version

### PR DESCRIPTION
**Pull request by B3nCr**
Update angular to latest version and fix LayoutController to use minification syntax. Change layout.html to use minified version of bundle.

### CODE REVIEW

**Comment by B3nCr** [comment]
I've signed the agreement. and this is a related issue 
https://github.com/IdentityServer/IdentityServer3/issues/1434

**Comment by brockallen** [comment]
I started looking at this... seems like you did a bit more than just upgrading to NG 1.3 -- some of the minification and injection was change, but those were done to make debugging easier (with the tradeoff being that minification for those little bits weren't worth it). 

In any event -- a few of the pages aren't working the same. Permissions and consent. I've not tested enough to determine of all the others are still working the same.

**Comment by B3nCr** [comment]
Hi Brock

That's odd, I'm using the same version in my instance of IdSvr and haven't
seen an issue with the pages.

I'll back the minification back out again and see what's going on with the
consent page.

Thanks
Ben

**Comment by B3nCr** [comment]
Would you be able to provide me with some info about the errors. I've just done a full login with consent and then viewed permissions without issue.

**Comment by brockallen** [comment]
Sorry - I had checked in some code that broke the tests. Merge and try again, plz.

As for the broken NG -- it's as if the ng-show/hide aren't working anymore. I'll debug some more this weekend.

**Comment by B3nCr** [comment]
Hi Brock

Yeah the ng-show directive relies on css which is injected using script.
CSP prevents this being injected in angular 1.3. I thought I'd fixed that
by adding the csp css file separately.

I'll merge your changes now.

Thanks
Ben

**Comment by B3nCr** [comment]
Yeah, I've added angular-csp.css to the style bundle. It's being loaded in my version but I can't see in the layout.html where that style is enforced. It's got a template section `{stylesheets}` but presumably that can be overridden by configuration.

The main script is included separately from the `{scripts]` template. Perhaps this style sjeet should be separate too?

    <script src="{applicationPath}/assets/scripts.js"></script>
    {scripts}

**Comment by brockallen** [comment]
#1478 used instead. thanks!

**Comment by apuchkov** [comment]
`angular-csp.css` should probably be included separately from the bundle indeed. 

I was working on custom styles for IdServ and cleared all stylesheets `viewOptions.Stylesheets.Clear();` before adding my custom style sheets. "Error:" and "External Login" started to be always visible on the login page. I thought that something wrong with my custom layout or angular, before I discovered that `angular-csp.css` was inadvertently removed.

`angular-csp.css` contains essential styles, which can be mistakenly removed when people just want to tweak styles.

**Pull request closed without merging**
