### PR TITLE
IE 8 Compatibility 

### PR DESCRIPTION
**Pull request by OsmanMElsayed**
#1218

### CODE REVIEW

**Comment by OsmanMElsayed** [comment]
Unfortunately, `textContent` is not the only one showstopper. There is a bigger issue which is [AngularJS 1.3+ doesn't support IE8](https://groups.google.com/forum/#!topic/angular/xXqJCkCEt38)
So, it is a trade-off between the two options: **AngularJS 1.3+** & **IE8**
I would opt for IE8 support taking into consideration the considerable amount of users who are still using Windows 7 which came with IE8 as the default OS user-agent.
So, would u mind downgrading to Angular JS 1.2.9?

**Comment by brockallen** [comment]
> So, would u mind downgrading to Angular JS 1.2.9?

Sorry, this will not happen. We never intended to support IE8 and Microsoft doesn't support it either.

**Comment by OsmanMElsayed** [comment]
Yea, this is true. IE8 is dead, so, why support a dead species.
However, no need to check whether `textContent` is supported or not. [Apparently, it is supported by every singe browser except IE8](http://caniuse.com/#search=textContent).

**Comment by brockallen** [comment]
Yep, fair enough -- I can merge this this weekend.

**Comment by brockallen** [comment]
ok done, thanks!

**Pull request merged**
