### PR TITLE
Support additional query string parameters for login page

### PR DESCRIPTION
**Pull request by denisbollinne**
Hello,

We made the following changes to support additional query string parameters to be sent to the login page. (related to #2312)

Let me know if additional changes needs to be done.

Regards,

### CODE REVIEW

**Comment by uncleyo** [comment]
I believe dependency on System.Web would be a "no go"

**Comment by denisbollinne** [comment]
Right, my bad, i'll update that one

**Comment by denisbollinne** [comment]
Ok I've just pushed the changes to remove the dependecy on system.web

**Comment by brockallen** [comment]
I don't think this type of change is something we're ready to accept, as we feel it's unnecessary. `acr_values` is the designated place to pass custom params, and so your login page can access those and then do anything it needs to with them. Sorry.

**Comment by denisbollinne** [comment]
Thanks for your feedback.

However, we couldnt find another way to handle the case that an end-user
bookmarks the login page.

Thats why we've pushed some arc_values to queryString parameters to keep
some "context" about the client app, without the need of having a valid
signIn token.

Kr,

**Comment by brockallen** [comment]
You can always read the signin message on your login page, read the client id, and the redirect back to yourself with the client_id param.

**Pull request closed without merging**
