### PR TITLE
Handling exceptions thrown by custom grant validator

### PR DESCRIPTION
**Pull request by dariusdamalakas**
Any exceptions thrown from custom grant validator should not bubble up the stack, but isntead should be returned as failed CustomGrantValidationResult, and error logged via logger.

### CODE REVIEW

**Comment by dariusdamalakas** [comment]
Does this look ok?

**Comment by leastprivilege** [comment]
hey! thanks!

I will look into this ASAP. But I am very busy right now.

**Comment by dariusdamalakas** [comment]
Cool, take your time. This is a fix as part of the #2151.

**Comment by leastprivilege** [comment]
cool! thanks!

**Comment by dariusdamalakas** [comment]
Super.  Is there a target / or schedule for the next release? (i.e. want to know when to expect a nuget).

**Comment by leastprivilege** [comment]
pretty soon - we are readying a 2.2.1 release

**Comment by leastprivilege** [comment]
2.2.1 is released.

**Pull request merged**
