### PR TITLE
Use JsonWebKey instead of certificate in ISigningKeyService

### PR DESCRIPTION
**Pull request by omerlh**
Hey
This is just a quick demonstration of the way I think we should solve #2727.
The code is completed, and all the tests are passing except the test that check what types are exposed - I think it failed because the `ISingingKeyService` public method return `JsonWebKey` from `Microsoft.IdentityModel.Protocols` assembly.
I will fix it and add some tests, but I first want to discuss if this is a good approach to fix this issue.
Thanks,
Omer

### CODE REVIEW

**Comment by omerlh** [comment]
I need some more time to review the CLA with my employer, I thought he also received a copy of the doc before signing it. Please cancel my signature until further update.

**Comment by leastprivilege** [comment]
Hi, 

thanks - and as I said - this would be a breaking change. So we cannot do that right now.

The other problem with that PR is that it is against master. But don't worry about it right now.

**Comment by omerlh** [comment]
Hi
Thank you for the response :)
This mean that sometime in the future this PR will be accepted? If so, what do you say about releasing a pre-release version with this change? I know that also MattCotterellNZ is looking forward for this, and I guess that it is critical for anyone else that is planing to use keyvault...

**Comment by leastprivilege** [comment]
This would need to go into 3.0.0 - and this will take a little bit more. I will check your code and validate it against other scenarios we have.

then again - I can't believe that azure keyvault does not allow using x509 certs (even if that code is a bit uglier).

**Comment by omerlh** [comment]
Yes, you can but the code is pretty ugly. What is hard it to make it play with identity server - it is pretty much a mess because of the current structure of the identity server, both MattCotterellNZ  and I tried to think it through and doesn't look like something feasible. That's why I've created this PR.

**Comment by leastprivilege** [comment]
I don't know enough about Azure KeyVault. 

Anyways - you know the constraints. We won't make that change anytime soon.

**Comment by omerlh** [comment]
Ok. Thanks. If by any chance you have a way to release it as a pre-release package it will be great.

**Comment by omerlh** [comment]
Hey
I've thought about something during the weekend - as far as I know the validation package assume that the x5c property in the JWK contains a certificate. This property is not required by the RFC, which mean that if this PR will be accepted someone could accidentally forgot to assign it a value and the validation of the JWT will fail. I think we should do one of the following - either remove the dependency on the x5c (I am not sure it will be easy) or enforce somehow that this property is set. What do you think?

**Comment by leastprivilege** [comment]
As I said before - I am not planning on accepting this PR anytime soon.

Once the time has come we start thinking about breaking changes (v3.0) - this feature needs a re-design.  Not sure then if JWK is the way to go - or the new SecurityKey abstraction in the upcoming Microsoft library. Something that will work for both idsrv3 and idsrv4.

This is such a central thing - it needs careful design.

If you can workaround it with the current extensibility points - that would be my recommendation.

Nevertheless - I will have a look at your code. That's why I leave this PR open.

**Comment by omerlh** [comment]
Ok, thanks

**Comment by omerlh** [comment]
Hey,
I've published a small adapter as a [nuget ](https://github.com/Soluto/IdentityServer.Contrib.JsonWebKeyAdapter)package. We are using it as a temporary solution for now, and I thought that might help for others with similar problems.

**Comment by leastprivilege** [comment]
IdentityServer3 will stay on X509 for the time being. In IdentityServer4 we have a more flexible infrastructure now.

**Pull request closed without merging**
