### PR TITLE
Scrub user passwords from logs

### LINKED ISSUE #2038: Scrub passwords from logs
Is there a way to scrub/sanitize the passwords when logging?

The [TokenRequestValidator logs the entire validated request](https://github.com/IdentityServer/IdentityServer3/blob/a6e2b6bdfd1516af6cd9fdc9f46a08bb23bb553e/source/Core/Validation/TokenRequestValidator.cs#L702) which includes the password. This is seen as security issue for us.

Thanks.

### PR DESCRIPTION
**Pull request by ayoung**
Closes #2038.

I added a ctor parameter to `TokenRequestValidationLog` to configure whether to scrub user passwords. This should be expanded to expose this configuration through the `LoggingOptions` but I wasn't sure if you wanted to make that change yet because it would effectively change the API -- though it is an addition to the interface, thus making it backwards compat.

Also, I refactored the logging to not serialize unless the logger is configured for that log level.

### CODE REVIEW

**Comment by ayoung** [comment]
Should I go ahead and expose this through `LoggingOptions`?

**Comment by leastprivilege** [comment]
no. there is not good reason for ever wanting the passwords in logs.

**Comment by ayoung** [comment]
Ok. I'll remove the bool from the `TokenRequestValidationLog` constructor.

**Comment by leastprivilege** [comment]
I merged manually. 

If you come across more data that needs to be removed - feel free to add more PRs.

thanks!!

**Pull request closed without merging**
