### PR TITLE
Show jwks without cert

### PR DESCRIPTION
**Pull request by omerlh**
Hey
I am working (as you might noticed :)) on using identity server without a certificate. So far so good, but the discovery endpoint does not show the JWK url if there is no signing certificate present in the options. I've tried to fix it by skipping the check - whether the user set the signing certificate.
Thanks,
Omer

### CODE REVIEW

**Comment by leastprivilege** [comment]
I told you already that in the 2.x branch there is nothing more we can do for that. I am not going to make all kind of hacky changes to accommodate a single scenario.

I have a different customer that uses key vault just fine with his x509 certs.

**Comment by omerlh** [comment]
This is not a huge change and this is necessary - otherwise I will have to create some dummy certificate only to make this work. As I said before, I don't have the private key so I cannot create a matching certificate.

**Comment by leastprivilege** [comment]
you need a public key - not a private key.

**Comment by leastprivilege** [comment]
.. and how do yo sign your JWTs?

**Comment by leastprivilege** [comment]
Maybe I am missing that piece - but does key vault support signing JWTs (or a serialized JWT) ? If yes - where can I read about that?

That would be a compelling reason to change things for the next breaking release.

**Comment by omerlh** [comment]
Yes, you are correct. You can work with key vault in HSM mode - which mean that the private key is always in the keyvault (like in HSM) and you call to an api in keyvault for signing (see the api [here](https://msdn.microsoft.com/en-us/library/microsoft.azure.keyvault.keyvaultclient.aspx)). You are right the I can create a certificate only with public key, and this is what I am doing for make the discovery endpoint to work. I am actually right now working on contribution package that will do the transformation between JsonWebKey to X509Certificate until the change in identity server 3 will be accepted.
Anyway, this change is really small (unless I am missing something) and it is really important to us - I don't want to create a certificate only to be able to expose the jwks url in the discovery endpoint...

**Comment by leastprivilege** [comment]
And why exactly do you need that url to included? for the middleware to work?

And what should that URL then return? an empty keyset?

**Comment by omerlh** [comment]
Yes, for the middleware.
The URL is using the signing key service which I've implemented over KeyVault. This is already working, the only thing that missing is this...



On Mon, Apr 4, 2016 at 8:30 AM -0700, "Dominick Baier" <notifications@github.com<mailto:notifications@github.com>> wrote:


And why exactly do you need that url to included? for the middleware to work?

And what should that URL then return? an empty keyset?

-

**Comment by omerlh** [comment]
Hey,
Any updates regarding that?
Thanks

**Comment by leastprivilege** [comment]
yes - I am busy. Will look into it ASAP.

**Comment by leastprivilege** [comment]
So what should I show then on the jwks_uri if there is no cert configured? An empty keys array? How will the middleware deal with that??

**Comment by omerlh** [comment]
The jwks_uri endpoint is using the SigningKeyService any way, as far as I know, and not using directly the certificate. So, I think this a problem of the SigningKeyService...

**Comment by leastprivilege** [comment]
How is that answering my question? Have you tried how the middleware behaves with an "empty" jwks_uri?

**Comment by omerlh** [comment]
The jwk uri will not return empty list as I will implement the SigningKeyService to return the public keys from the KeyVault.

**Comment by leastprivilege** [comment]
OK - tonight I will have a look and push a package to the CI feed if that's feasible.

**Comment by omerlh** [comment]
Ok, thank you very much!

**Comment by leastprivilege** [comment]
OK - i made the change manually.

**Comment by omerlh** [comment]
OK thanks

**Comment by omerlh** [comment]
Hey
Another thing that I've noticed - the ````UseIdentityServerExtension```` class check if the signing certificate exist and if not it raise an error. I can ignore this error, so this is not urgent, but if possible - it will be great to not raise an error if there is no signing certificate. What do you think?
Thanks,
Omer

**Pull request closed without merging**
