### PR TITLE
Update app.js

### PR DESCRIPTION
**Pull request by shabatinT**
We have a lot of customers who still using IE8. But IE8 doesn't support "textContent" http://www.w3schools.com/jsref/prop_node_textcontent.asp

With proposed change all should work even under IE8.

Thanks.

### CODE REVIEW

**Comment by henninga** [comment]
I'd rather check to see if textContent is available and fall back to innerHTML if not

**Comment by brockallen** [comment]
we don't accept PRs on master -- please read the contributing guidelines

**Comment by shabatinT** [comment]
In the contributing guide line(https://github.com/IdentityServer/IdentityServer3/blob/master/CONTRIBUTING.md) there is nothing about the branches. Can you please update it?

**Comment by shabatinT** [comment]
You can also contribute by submitting pull requests with code changes.

**Comment by brockallen** [comment]
It states: _We only accept PRs to the dev branch._

**Pull request closed without merging**
